const aftershave = [
  {
    id: 1,
    name: "Dior Sauvage",
    perfumer: "Francois Demachy",
    brand: "Dior",
    trending: "yes",

    scentProfile: [
      "Calabrian Bergamot",
      "Pepper",
      "Sichaun Pepper",
      "Lavender",
      "Pink Pepper",
      "Vetiver",
      "Patchouli",
      "Geranium",
      "Elemi",
      "Ambroxan",
      "Cedar",
      "Labdanum ",
    ],
    image: "@/src/images/Dior-Sauvage.jpg",
    occasion: "Anytime",
    season: "spring",
    review:
      "There was a time a few years ago where you couldn't go out and not smell someone wearing Dior Sauvage. The scent in one word is beautiful. You can wear it in a suit, with a polo, while on holiday. This fragrance is initially citrusy, however, its real power is clear when it is given time. The notes of Sichaun Pepper, Lavender, Nutmeg & Star Anise pops and it becomes full of life. Sweet, Spicy & Citrusy, widely regarded as the only blue fragrance that your collection will ever need.",
    link: "https://www.boots.com/dior-sauvage-eau-de-parfum-60ml-10243636?CAWELAID=620000410000469072&cm_mmc=bmm-buk-bing-ppc-_-PLAs-_-Fragrance-_-UK_Smart_Shopping_Fragrance&gclid=08e4a58fcef71c01bf35c0a2600baa7d&gclsrc=3p.ds&msclkid=08e4a58fcef71c01bf35c0a2600baa7d&utm_source=bing&utm_medium=cpc&utm_campaign=UK_Smart_Shopping_Fragrance&utm_term=4578366468564331&utm_content=Fragrance",
  },
  {
    id: 2,
    name: "Creed Aventus",
    perfumer: "Olivier Creed",
    brand: "Creed",
    trending: "yes",
    scentProfile: [
      "Pineapple",
      "Bergamot",
      "Black Currant",
      "Apple",
      "Birch",
      "Patchouli",
      "Moroccan Jasmine",
      "Rose",
      "Musk",
      "Oak Moss",
      "Ambergris",
      "Vanille",
    ],
    image: "@/src/images/Creed-Aventus.jpg",
    occasion: "Anytime",
    season: "spring",
    review:
      "Aventus put Creed on the map and is known as truly exceptional and sophisticated fragrance. This scent is renowed for its luxurious and unique blend of notes, offering a captivating experience. The love for this scent comes from the mix of blackcurrent, pineapple, jasmine, patchouli and rose. It is unique as it doesnt smell citrusy or floral but rather a mix of both. It is the epitome of versatility, the most sold niche fragrance of the 21st century and is perfect for special occasions, weddings, formal events, and it leaves a lasting and remarkable impression. In addition to this, it performs well in all seasons, making it an excellent year-round choice.",
    link: "https://www.notino.co.uk/creed/aventus-eau-de-parfum-for-men/p-628844/?gad_source=1&gclid=Cj0KCQjw4bipBhCyARIsAFsieCwATBdGhQ9Qwis3D0azPvHD38XqqH6CfWTsfHvy5NvFb8fZA_YQqboaApoiEALw_wcB",
  },
  {
    id: 3,
    name: "Myrrh & Tonka",
    perfumer: "Mathilde Bijaoui",
    brand: "Jo Malone",
    trending: "yes",
    scentProfile: ["Lavender", "Myrrh", "Tonka Bean", "Vanilla", "Almond"],
    image: "@/src/images/MyrhhandTonka.jpg",
    occasion: "Date Night",
    season: "autumn",
    review:
      "Simply put, Myrrh & Tonka is the jewel in Jo Malone's fragrance crown. A personal favourite of mine for a date night or when you need to dress to impress, there is an atmosphere of addiction and carnal richness to this fragrance which appeals to both men and women. At the top there is a hint of lavender and almond introduces you to a sweet scent. The big, rich heart and base note of myrhh is sensual and the tonka brings depth. Its is perfect for fall and winter, as its cozy and comforting character complements the colder months.",
    link: "https://www.jomalone.co.uk/product/25946/110447/colognes/myrrh-tonka-cologne-intense",
  },
  {
    id: 4,
    name: "Black Phantom",
    perfumer: "Sidonie Lancesseur",
    brand: "By Killian",
    trending: "yes",
    scentProfile: [
      "Dark Chocolate",
      "Rum",
      "Caramel",
      "Coffee",
      "Sugar Cane",
      "Almond",
      "Sandalwood",
      "Heliotrope",
    ],
    image: "@/src/images/Black-Phantom.jpg",
    occasion: "Date Night",
    season: "winter",
    review:
      "I can genuinely say 1000 words about this fragrance. This was my first fragrance from By Killian and it previously ruled that brand until Angel Share came along. This fragrance is a killer as a quick search on the Killian fragrances website will show you that it is made from Cyanide. Enough of anything can be deadly so it is lucky they controlled it by getting it from crushed Almonds. This is the ultimate gourmand fragrance with there being hints of rum, coffee and chocolate. ",
    link: "https://www.johnlewis.com/kilian-paris-back-to-black-eau-de-parfum-50ml/p4931129?size=50ml&s_ppc=5dx92700074071294720_mixed_fashion_BAU&tmad=c&tmcampid=2&msclkid=e340792876ee15625d621c06b49c3009&gclid=e340792876ee15625d621c06b49c3009&gclsrc=3p.ds",
  },
  {
    id: 5,
    name: "Valentino Uomo Intense",
    perfumer: "Antoine Maisondieu & Guillaume Flavigny",
    brand: "Valentino",
    trending: "yes",
    scentProfile: [
      "Mandarin Orange",
      "Clary Sage",
      "Tonka Bean",
      "Iris",
      "Vanilla",
      "Leather",
    ],
    image: "@/src/images/Valentino-Uomo.jpg",
    occasion: "Date Night ",
    season: "autumn",
    review:
      "This is a very sophisticated and captivating fragrance. I consider this fragrance timeless with its unique blend of warm, rich and sensual notes. The combination of Iris and Tonka Bean adds a sweetness. The real unique combination is the leather and vanilla which meshes together to add depth. This is a fantastic fragrance for evening wear, making it an ideal choice for those who want to leave a lasting impression, and it is everpresent in my rotation. ",
    link: "https://www.amazon.co.uk/Valentino-Man-Intense-Parfum-Spray/dp/B01GD2H1BY/ref=sr_1_2?crid=2TIHTZ9NLNYE9&keywords=valentino+uomo+intense&qid=1697563321&sprefix=valentino+uom%2Caps%2C107&sr=8-2",
  },
  {
    id: 6,
    name: "Mojave Ghost",
    perfumer: "Ben Gorham",
    brand: "Byredo",
    trending: "yes",

    scentProfile: [
      "Sapodilla",
      "Ambrette",
      "Magnolia",
      "Violet",
      "Sandalwood",
      "Ambergris",
      "Cedar",
    ],
    image: "@/src/images/Mojave-Ghost.jpg",
    season: "spring",
    occasion: "Night Out ",
    link: "https://www.amazon.co.uk/Byredo-Mojave-Ghost-Parfum-100/dp/B00NAX07ZM/ref=sr_1_1?crid=3LO8KJQASAFTB&keywords=mojave+ghost+byredo&qid=1697563371&sprefix=mojave+%2Caps%2C112&sr=8-1&ufe=app_do%3Aamzn1.fos.cc223b57-2b86-485c-a85e-6431c1f06c86",
  },
  {
    id: 7,
    name: " Y Eau de Parfum",
    perfumer: "Dominique Ropion",
    brand: "Yves Saint Laurent",
    scentProfile: [
      "Apple",
      "Ginger",
      "Bergamot",
      "Sage",
      "Juniper Berries",
      "Geranium ",
      "Cedar",
      "Vetiver",
      "Olibanum",
    ],
    image: "@/src/images/y.jpg",
    occasion: "office ",
    season: "summer",
    review:
      "This is a modern classic that strikes a perfect balance between freshness and sophistication. The combination of bergamot and ginger gives you an initial hit of citrus and spice and the cedarwood and vetiver give it a long lasting , woody scent. This combination means that it is fresh enough to be worn in the spring and summer but also long lasting and potent enough to be worn in the autumn and winter. It is perfect for both daytime and evening wear, making it a fantastic choice for those who appreciate a versatile and confident scent, however, we do believe that it becomes truly magical in the summer months. ",
    link: "https://www.amazon.co.uk/Yves-Saint-Laurent-3614272050358-100ML/dp/B07GB6B37N/ref=sr_1_1?crid=1I1FR0S16D1GB&keywords=y+eau+de+parfum+yves+saint+laurent&qid=1697563782&sprefix=y+ea%2Caps%2C130&sr=8-1",
  },
  {
    id: 8,
    name: "Jardin Exclusif",
    perfumers: "Mancera",
    brand: "Mancera",
    scentProfile: [
      "Pear",
      "White Peach",
      "Caramel",
      "Lemon",
      "Black Currant",
      " Green Apple",
      "Sicilian Orange",
      "Jasmine",
      "Ambergris",
      "Violet",
      "Bulgarian Rose",
      "White Musk",
      "Madagascar Vanilla",
      "Sandalwood",
    ],
    image: "@/src/images/Jardin-Exclusif.jpg",
    occasion: "formal events ",
    season: "summer",
    review:
      "This is one of the most fancy fragrances I have smelt and truthfully a masterpiece. It has exquisite blend of floral and woody notes, it's perfect for someone who seeks an elegant and lasting impression. The jasmine and ambergris gives off the vibe of a floral bouquet but with even more depth. This is a perfect scent for special occasions, formal events, or intimate evenings, as it is sophisticated and memorable. Whether you're attending a gala or simply want to feel exceptional on a romantic date, this will truly set you apart.",
    link: "https://www.selfridges.com/GB/en/cat/mancera-jardin-exclusif-eau-de-parfum-120ml_1119-3006532-55052/",
  },
  {
    id: 9,
    name: "Le Male Le Parfum ",
    perfumer: "Quentin Bisch & Natalie Gracia-Cetto",
    brand: "Jean Paul Gaultier",
    scentProfile: [
      "Cardamom",
      "Lavender",
      "Iris",
      "Vanilla",
      "Oriental Notes",
      "Woodsy Notes",
    ],
    image: "@/src/images/lemale.jpg",
    season: "autumn",
    occasion: "Night Out ",
    review:
      "The original Le Male was a JPG classic but this is a modern interpretation that is significantly richer. Its opening notes of cardamom and lavender gives off an initial spice, while the iris and vanilla bring depth and sensuality to the composition. The base notes of oriental woods and tonka bean provide a warm and lasting presence. This is a memorable fragrance and you should use it for that purpose such as formal events and romantic dinners, as it would allow you to make a strong statement.",
    link: "https://www.johnlewis.com/jean-paul-gaultier-le-male-le-parfum/p5123628?size=125ml&s_ppc=5dx92700074071294720_mixed_fashion_BAU&tmad=c&tmcampid=2&gclid=0b504928d3cd1601bb142c06162214c1&gclsrc=3p.ds&msclkid=0b504928d3cd1601bb142c06162214c1",
  },
  {
    id: 10,
    name: "The One for Men",
    perfumer: "Olivier Polge",
    brand: "Dolce & Gabbana",
    scentProfile: [
      "Grapefruit",
      "Coriander",
      "Basil",
      "Ginger",
      "Cardamom",
      "Orange Blossom",
      "Amber",
      "Tobacco",
      "Cedar",
    ],
    image: "@/src/images/The-One.jpg",
    occasion: "Date Night ",
    season: "autumn",
    review:
      "This fragrance is often described as warmth in a bottle, the undisputed best date night fragrance. The formula is a classic and sophisticated. It starts of very citrusy with grapefruit and coriander but the mix of cardomom and tobacco adds a spicy, smokey feel with complexity. It exudes an air of understated elegance and confidence. It is perfect for both daytime and evening wear, making it a fantastic choice for any occasion. It's a great option for formal events, business meetings, or casual outings, but this is still the undisputed king of date night fragrances.",
    link: "https://www.amazon.co.uk/Dolce-Gabbana-100-Perfume-Water/dp/B074L61FXT/ref=sr_1_2?crid=26BBKZP2JVO9J&keywords=the+one+dolce+and+gabbana+for+men&qid=1697564198&sprefix=the+one+%2Caps%2C85&sr=8-2",
  },
  {
    id: 11,
    name: "Mercedes Benz Club Black",
    perfumer: "Olivier Cresp",
    brand: "Mercedes-Benz",
    scentProfile: [
      "Bergamot",
      "Incense",
      "Jasmine",
      "Vanilla",
      "Benzoin",
      "Woodsy Notes",
      "Ambroxan",
    ],
    image: "@/src/images/Mercedes.jpg",
    occasion: "night out ",
    season: "winter",
    review:
      "This is a modern fragrance with a unique blend of notes. The top notes of bergamot, cardamom, and black pepper, it opens with a fresh and spicy allure that is both invigorating and stylish. It then dries down into something with a lot more character, elegance and depth with the introduction of lavender and violet. It is versatile enough to be worn all year round but it truly shines in the evening, making it perfect for nights out, dinners, or special occasions. It is a great addition to your collection if you want a refined scent that embodies sophistication and luxury.",
    link: "https://www.amazon.co.uk/Mercedes-Benz-Club-Black-Toilette-Spray/dp/B0787F9GCC/ref=sr_1_1?crid=3TA0UX6AHOQB&keywords=mercedes+benz+club+black&qid=1697564240&sprefix=Merce%2Caps%2C132&sr=8-1",
  },
  {
    id: 12,
    name: "Club de Nuit Intense Man",
    perfumer: "Armaf",
    brand: "Armaf",
    scentProfile: [
      "Lemon",
      "Pineapple",
      "Bergamot",
      "Apple",
      "Birch",
      "Jasmine",
      "Rose",
      "Musk",
      "Ambergris",
      "Patchouli",
      "Vanilla",
    ],
    occasion: "Anytime",
    season: "spring",
    image: "@/src/images/ClubDeNuit.jpg",
    review:
      "A quick question for you. Do you know what the best selling, most desired and most popular mens fragrance of the 21st century is? No? The answer is Creed Aventus. Me selecting Club De Nuit Intense Man by Armaf goes against everything I believe in. Clones don't tend to be in my vocabulary ,however, when it is of the most popular aftershave, for 1/8 of the price then you can't really go wrong. The scent has a combination of bold tones of citrus, wood and spice. The use of lemon, pineapple, and blackcurrant means that the fragrance is good as a fresh summer fragrance. In addition to this, ambergris, vanilla and patchouli adds the spice necessary for a fragrance to be used in the autumn and winter months. There are also some who believe that due to the recent reformulation of Aventus, they prefer Club De Nuit as it tends to last longer and perform better. It has exceptional longevity that lingers throughout the night, making it ideal for formal events, romantic dinners, or upscale gatherings, for around £30. A quick caveat on this fragrance. You cannot just spray this and leave, spray the fragrance wait 15 minutes and let the initial harsh base disperse .",
    link: "https://www.amazon.co.uk/Armaf-Club-Nuit-Intense-105ml/dp/B00M3IFUMK/ref=sr_1_1?crid=WHPUHU3A2S82&keywords=club+de+nuit+intense+man&qid=1697564297&sprefix=Club+%2Caps%2C181&sr=8-1",
  },
  {
    id: 13,
    name: "Bentley For Men Absolute",
    perfumer: "Michel Almairac",
    brand: "Bentley",
    scentProfile: [
      "Pink Pepper",
      "Ginger",
      "Olibanum",
      "Papyrus",
      "Sandalwood",
      "Atlas Cedar",
      "Agarwood",
      "Amber",
      "Moss",
    ],
    image: "@/src/images/BentleyAbsolute.jpg",
    review:
      "What do you usually associate with Bentleys, a sharp suit, glasses, clean shaven or if not, neat stubble. Yes a man ready for work. Well this is a fragrance that is fairly dapper but not overly mature so it is applicable for school. Initially this fragrance starts very spicy and boozy but deviates from that after half an hour to something more captivating with the papyrus and sandalwood. It is excellent for autumn and winter, as it thrives in the cooler seasons. It is perfect for both daytime and evening wear, making it a versatile option for various occasions. Whether you're dressing for a formal event or enjoying a cozy night out, this fragrance will leave a lasting impression.",
    season: "summer",
    link: "https://www.amazon.co.uk/Absolute-Bentley-Eau-Parfum-100ml/dp/B01HICDFSQ/ref=sr_1_1?keywords=bentley+for+men+absolute&qid=1690975793&sprefix=bentley+for+m%2Caps%2C143&sr=8-1",
  },
  {
    id: 14,
    name: "Halloween Man X",
    perfumer: "Nicolas Beaulieu",
    brand: "Halloween",
    scentProfile: [
      "Cardamom",
      "Lavender",
      "Lemon",
      "Coffee",
      "Whiskey",
      "Cinnamon",
      "Leather",
      "Mineral Notes",
      "Tonka Bean",
      "Amber",
      "Incense",
    ],
    season: "winter",
    review:
      "This is a fragrance that I was apprehensive in initially trying but this is a serious attention grabber. It has absolutely no citrusy notes and opens up with cardamom and lavender for a blend of spice and freshness. The best thing about this fragrance is that it lives up to the name 'Halloween Man X' as the most prominent notes are cinnamon and whisky which add warmth. It is ideal for the cooler months of autumn and winter but is also a memorable fragrance that lasts well into the night, making it perfect for formal events, romantic dates or when you want to leave a lasting impact. ",
    image: "@/src/images/Halloween.jpg",
    link: "https://www.amazon.co.uk/Halloween-Toilette-Oriental-Foug%C3%A8re-Fragrance/dp/B07NPQMY15/ref=sr_1_1?crid=28147JSNKB0EL&keywords=halloween+man+x&qid=1697564417&sprefix=Halloween+man%2Caps%2C119&sr=8-1",
  },
  {
    id: 15,
    name: "Terre d'Hermès",
    perfumer: "Jean-Claude Ellena",
    brand: "Hermès",
    scentProfile: [
      "Orange",
      "Grapefruit",
      "Pepper",
      "Pelargonium",
      "Vetiver",
      "Cedar",
      "Patchouli",
      "Benzoin",
    ],
    season: "autumn",
    image: "@/src/images/Terre.jpg",
    review:
      "This is known for its elegent and earthy character. The start of the fragrance is very citrusy, focusing mainly on orange and grapefruit but it comes a lot more balanced with pepper and geranium which adds spice and floral tones. It is suitable for year-round wear, but it particularly shines in the transitional seasons of spring and autumn when its natural and woody notes complement the changing environment. It is perfect for both daytime and evening wear, making it a versatile choice for various occasions, from casual outings to formal events. This fragrance is a classic, well-crafted scent that will honestly stand the test of time.",
    link: "https://www.amazon.co.uk/Hermes-Terre-DHermes-Toilette-Spray/dp/B000JLCW56/ref=sr_1_2?crid=T3TBJVR72OO7&keywords=terre%2Bd%27hermes%2Bperfume%2Bfor%2Bmen&qid=1697564447&sprefix=Terr%2Caps%2C245&sr=8-2&th=1",
  },
  {
    id: 16,
    name: "Bleu de Chanel",
    perfumer: "Jacques Polge",
    brand: "Chanel",
    scentProfile: [
      "Grapefruit",
      "Lemon",
      "Mint",
      "Pink Pepper",
      "Ginger",
      "Nutmeg",
      "Jasmine",
      "Incense",
      "Vetiver",
      "Cedar",
      "Sandalwood",
      "Patchouli",
      "Labdanum",
      "White Musk",
    ],
    season: "summer",
    image: "@/src/images/BDC.jpg",
    review:
      "This is a fragrance that you could wear all year, making it a reliable choice for various occasions. It's suitable for both daytime and evening use , whether you're headed to the office, out fora casual dinner, or dressing up a special event. It is very fresh, starting off with notes of lemon and mint and then becomes a significantly more balanced with the additions of ginger, nutmeg, cedar and sandalwood. It is considered a timeless classic and exudes and air of confidence and elegance that very few fragrances can match.",
    link: "https://www.johnlewis.com/chanel-bleu-de-chanel-eau-de-parfum-spray/p1705370",
  },
  {
    id: 17,
    name: "Dior Homme 2020",
    perfumer: "Francois Demachy",
    brand: "Dior",
    scentProfile: [
      "Bergamot",
      "Pink Pepper",
      "Elemi",
      "Cashmere Wood",
      "Atlas Cedar",
      "Patchouli",
      "Haitian Vetiver",
      "White Musk",
    ],
    season: "summer",
    review:
      "This scent is a contemporary interpretation of a classic, offering a unique experience. With top notes of bergamot and pink pepper, it opens with a fresh and citrusy burst that exudes energy. The heart notes of iris and rose add depth and elegance.The cedar and vanilla add warmth to the fragrance and ensures the fragrance lingers. I genuinely think this is a perfect versatile fragrance as it isn't out of place in the daytime and the evening. It is particularly good in a formal setting where a suit is a necessity. Try this scent if you enjoy well-crafted scents that reflect confidence and refinement.",
    image: "@/src/images/Dior-Homme.jpg",
    link: "https://www.amazon.co.uk/CD-DIOR-HOMME-EDT-VP/dp/B0842NM51Y/ref=sr_1_1?crid=2AY1IMV4ETX45&keywords=dior+homme+2020&qid=1697564589&sprefix=dior+homme+2020%2Caps%2C115&sr=8-1",
  },
  {
    id: 18,
    name: "Prada L'Homme",
    perfumer: "Daniela (Roche) Andrier",
    brand: "Prada",
    scentProfile: [
      "Neroli",
      "Black Pepper",
      "Cardamom",
      "Carrot Seeds",
      "Iris",
      "Violet",
      "Geranium",
      "Amber",
      "Cedar",
      "Patchouli",
      "Sandalwood",
    ],
    occasion: "office",
    image: "../src/Prada.jpg",
    review:
      "This is my main office/professional scent. It is wildly elegant and versatile with top notes of neroli and black pepper, it opens up as simultaneously fresh and spicy. The Iris and violet adds a powdery and floral essence which balances the aroma. As I said, I wear this a lot to the office. This is because it is very versatile and able to be worn all year round regardless of daytime and evening occasions.",
    link: "https://www.amazon.co.uk/Prada-LHOMME-LEAU-100ml-Toilette/dp/B07BB2PRP1/ref=sr_1_1?crid=242C7U3VP26MJ&keywords=prada+l%27homme&qid=1697564623&sprefix=Prada+L%27h%2Caps%2C194&sr=8-1",
    season: "summer",
  },
  {
    id: 19,
    name: "Nautica Voyage",
    perfumer: "Maurice Roucel",
    brand: "Nautica",
    scentProfile: [
      "Apple",
      "Green Leaves",
      "Lotus",
      "Mimosa",
      "Musk ",
      "Cedar",
      "Oakmoss",
      "Amber",
    ],
    occasion: "anytime",
    season: "summer",
    link: "https://www.amazon.co.uk/Nautica-Voyage-Toilette-Spray-Authentic/dp/B01I54ITP0/ref=sr_1_1?keywords=nautica+voyage&qid=1690588449&sprefix=nautic%2Caps%2C90&sr=8-1",
    image: "@/src/images/Nautica.jpg",
    review:
      "This is perfect for the summer as it is manufactored for a casual and active lifestyle. It opens up fairly crisp with notes of green apple and green leaves. It then becomes a lot more floral as the notes of lotus and mimosa become more prominent. It does best when there is heat as it forces its light and airy character shines the brightest. Its enduring freshness and sea inspired notes make it a great go to option for warm-weather activities. ",
  },
  {
    id: 20,
    name: "La Nuit de l'Homme",
    perfumer: "Anne Flipo, Pierre Wargnye and Dominique Ropion",
    brand: "Yves Saint Laurent",
    scentProfile: [
      "Cardamom",
      "Lavender",
      "Virginia Cedar",
      "Bergamot",
      "Vetiver",
      "Caraway",
    ],
    image: "@/src/images/La-Nuit-De-L'homme.jpg",
    link: "https://www.amazon.co.uk/Nuit-Yves-Saint-Laurent-Toilette/dp/B001WB1JNS/ref=sr_1_4?crid=29SMFQWP2G5K1&keywords=la+nuit+de+l%27homme&qid=1697565606&sprefix=la+nuit+d%2Caps%2C205&sr=8-4",
    season: "winter",
  },
  {
    id: 21,
    name: "Bvlgari Man Wood Neroli ",
    perfumer: "Alberto Morillas",
    brand: "Bvlgari",
    scentProfile: [
      "Neroli",
      "Bergamot",
      "Orange Blossom",
      "Virginia Cedar",
      "Cypriol Oil",
      "Woody Notes",
      "White Musk",
      "Ambergris",
      "Amber",
      "Leather",
    ],
    season: "summer",
    image: "@/src/images/Wood-Neroli.jpg",
    link: "https://www.amazon.co.uk/Bvlgari-Wood-Neroli-100ml-Parfum/dp/B07T73VKZC/ref=sr_1_1?crid=O43WL520QJAA&keywords=bvlgari+man+wood+neroli&qid=1697565634&sprefix=Bulgari+wood+%2Caps%2C82&sr=8-1",
  },
  {
    id: 22,
    name: "Stronger With You Intensely",
    perfumer: "Cecile Matton",
    brand: "Emporio Armani",

    scentProfile: [
      "Pink Pepper",
      "Juniper",
      "Violet",
      "Toffee",
      "Cinnamon",
      "Lavender",
      "Sage",
      "Vanilla",
      "Tonka Bean",
      "Amber",
      "Suede",
    ],
    link: "https://www.boots.com/emporio-armani-stronger-with-you-intensely-eau-de-parfum-50ml-10259447?cm_mmc=bmm-buk-google-ppc-_-PLAs_HeroCompare-_--_-PMax:+UK_Smart_Shopping_Fragrance_All&gad_source=1&gclid=Cj0KCQjw4bipBhCyARIsAFsieCxJA9BQVvAI4nNDsYUtvGZIuX1yHQn1X_yq9iKcJjGjxidxFPxZmagaAk-WEALw_wcB&gclsrc=aw.ds",
    image: "@/src/images/Stronger.jpg",
    season: "autumn",
  },
  {
    id: 23,
    name: "Spicebomb",
    perfumer: "Olivier Polge",
    brand: "Viktor & Rolf",

    scentProfile: [
      "Pink Pepper",
      "Elemi",
      "Bergamot",
      "Grapefruit",
      "Cinnamon",
      "Saffron",
      "Paprika",
      "Tobacco",
      "Leather",
      "Vetiver",
    ],
    image: "@/src/images/Spicebomb.jpg",
    link: "https://www.amazon.co.uk/Viktor-Rolf-Spicebomb-Extreme-Parfum/dp/B00WYP5ZHW/ref=sr_1_5?crid=3LH9SCM11A7SY&keywords=spicebomb&qid=1697565728&sprefix=spiceb%2Caps%2C243&sr=8-5&th=1",
    season: "winter",
  },
  {
    id: 24,
    name: "Artisan Pure",
    perfumer: "Rodrigo Flores-Roux",
    brand: "John Varvatos",
    scentProfile: [
      "Clementine",
      "Mandarin Orange",
      "Lemon",
      "Bergamot",
      "Thyme",
      "Marjoram",
      "Petitgrain",
      "Ginger",
      "Woody Notes",
      "Musk",
      "Orris Root ",
      "Amber",
    ],
    season: "summer",
    image: "@/src/images/Artisan-pure.jpg",
    link: "https://www.amazon.co.uk/John-Varvatos-Artisan-Pure-125/dp/B078218XMK/ref=sr_1_1?crid=1H6Q1EOHL2DMO&keywords=artisan+pure+john+varvatos&qid=1697565772&sprefix=Artisan+%2Caps%2C87&sr=8-1",
  },
  {
    id: 25,
    name: "Bentley for Men Intense",
    perfumer: "Nathalie Lorson",
    brand: "Bentley",
    scentProfile: [
      "Bay Leaf",
      "Black Pepper",
      "Bergamot",
      "Rum",
      "Cinnamon",
      "Woody Notes",
      "Clary Sage",
      "Leather",
      "Benzoin",
      "Patchouli",
      "Cedar",
    ],
    image: "@/src/images/BFMI.jpg",
    link: "https://www.amazon.co.uk/Bentley-Men-Intense-Eau-Parfum/dp/B00CP7A1BY/ref=sr_1_1?crid=1TRKRRY6WK267&keywords=bentley%2Bintense%2Bfor%2Bmen&qid=1697565804&sprefix=Bentl%2Caps%2C102&sr=8-1&th=1",
    season: "autumn",
    occasion: "office",
  },
  {
    id: 26,
    name: "Versace Blue Jeans",
    perfumer: "Jean-Pierre Bethouart",
    brand: "Versace",
    scentProfile: [
      "Citruses",
      "Bergamot",
      "Juniper",
      "Anise",
      "Brazilian Rosewood",
      "Basil",
      "Lavender",
      "Rose",
      "Carnation",
      "Heliotrope",
      "Jasmine",
      "Geranium",
      "Sage",
      "Fir",
      "Lily of the Valley",
      "Vanilla",
      "Tonka Bean",
      "Sandalwood",
      "Iris",
      "Musk",
      "Amber",
      "Cedar",
      "Vetiver",
      "Patchouli",
    ],
    image: "@/src/images/VBJ.jpg",
    link: "https://www.amazon.co.uk/Versace-Blue-Jeans-Toilette-Vaporizer/dp/B007W9ZEHQ/ref=sr_1_1?crid=2ZC698NHA52DN&keywords=versace%2Bblue%2Bjeans&qid=1697565872&sprefix=Versace%2B%2Caps%2C97&sr=8-1&th=1",
    season: "spring",
    review:
      " My dad got me into fragrance from when I was a child. I used to 'borrow' his fragrances because I wanted to be like him. I obviously couldnt continue to do this as these were expensive and dear fragrances. Versace Blue Jeans was the answer, the first fragrance he bought me that was my own. It is a casual and versatile fragrance with a citrusy opening and a touch of spice with nutmeg and violet to add a bit of spice. It is ideal for everyday wear, suitable for every season as it is clean and approachable, but it shines particularly well in the spring and summer when its freshness is most appreciated. It is light, easy to wear, and can be found for under £20 in most places so you can't really go wrong with it.",
    occasion: "anytime",
  },
  {
    id: 27,
    name: "Tobacco Vanille",
    perfumer: "Olivier Gillotin",
    brand: "Tom Ford",
    scentProfile: [
      "Tobacco Leaf",
      "Spicy Notes",
      "Vanilla",
      "Cacao",
      "Tonka Bean",
      "Tobacco Blossom",
      "Dried Fruits",
      "Woody Notes",
    ],
    season: "winter",
    image: "@/src/images/Tobacco-Vanille.jpg",
    link: "https://www.lookfantastic.com/tom-ford-tobacco-vanille-eau-de-parfum-spray-50ml/12709323.html?affil=thgppc&switchcurrency=GBP&shippingcountry=GB&gclid=55d2db7af4d11453d759be5439d3eb45&gclsrc=3p.ds&msclkid=55d2db7af4d11453d759be5439d3eb45&utm_source=bing&utm_medium=cpc&utm_campaign=UK%20Smart%20Shopping%20SSC%20-%20Top%2035%20Brands%20-%201000%25&utm_term=4583589124190261&utm_content=Top%2035%20Brands",
  },
  {
    id: 28,
    name: "Red Tobacco",
    perfumer: "Mancera",
    brand: "Mancera",
    scentProfile: [
      "Cinnamon",
      "Agarwood",
      "Incense",
      "Saffron",
      "Nutmeg",
      "Green Apple",
      "White Pear",
      "Patchouli",
      "Jasmine",
      "Tobacco",
      "Madagascar Vanilla",
      "Amber",
      "Guaiac Wood",
      "Sandalwood",
      "White Musk",
      "Haitian Vetiver",
    ],
    season: "winter",
    image: "@/src/images/Red-Tobacco.jpg",
    link: "https://www.bing.com/search?q=red+tobacco+mancera&cvid=c7bb952abee64fb3b51a923241dc4359&gs_lcrp=EgZjaHJvbWUqBAgCEAAyBAgAEAAyBggBEEUYOTIECAIQADIECAMQADIECAQQADIECAUQADIECAYQADIECAcQADIECAgQANIBCDI4MDJqMGo0qAIAsAIA&FORM=ANAB01&PC=HCTS",
  },
  {
    id: 29,
    name: "Eros",
    perfumer: "Aurelien Guichard",
    brand: "Versace",
    scentProfile: [
      "Mint",
      "Green Apple",
      "Lemon",
      "Tonka Bean",
      "Ambroxan",
      "Geranium",
      "Madagascar Vanilla",
      "Virginian Cedar",
      "Atlas Cedar",
      "Vetiver",
      "Oakmoss",
    ],
    image: "@/src/images/Eros.jpg",
    review:
      "This was the original clubbing scent, sensationally sweet. It isn't particulary unique as there are two other fragrances that accomplish a similar thing in Paco Rabanne 1 Million and Jean Paul Gaultier Ultramale, however, all of them are effective and there are subtle differences between them.",
    occasion: "Clubbing",
    link: "https://www.amazon.co.uk/Versace-Eros-Parfum-100-ml/dp/B09HXZ84SJ/ref=sr_1_2?crid=2H222IT0HIIE&keywords=versace+eros&qid=1697566063&sprefix=vers%2Caps%2C180&sr=8-2",
    season: "autumn",
  },
  {
    id: 30,
    name: "Armani Code",
    perfumer: "Antonie lie",
    brand: "Giorgio Armani",
    scentProfile: [
      "Lemon",
      "Bergamot",
      "Star Anise",
      "Olive Blossom",
      "Guaiac Wood",
      "Leather",
      "Tonka Bean",
      "Tobacco",
      "Liquorice",
    ],
    image: "@/src/images/Armani-code.jpg",
    review:
      "This is a loved fragrance by all. This is personally one of my favourites and is wildly unique as it is one of the only fragrances that uses liquorice as a note. It is also fairly versatile and not too harsh but you need to weary as it does not last particularly long.",
    occasion: "Anytime during the summer",
    link: "https://www.amazon.co.uk/Giorgio-Armani-Code-Parfum-60ml/dp/B08YYYX2TK/ref=sr_1_2?crid=GKDMHPBIYSK7&keywords=armani+code+perfume+men&qid=1697566093&sprefix=armani+%2Caps%2C130&sr=8-2",
    season: "summer",
  },
  {
    id: 31,
    name: "1 Million",
    perfumer:
      "Christophe Raynaud , Olivier Pescheux, Michel Girard, Christian Dussoulier",
    brand: "Paco Rabbane",
    scentProfile: [
      "Blood Mandarin",
      "Grapefruit",
      "Mint",
      "Cinnamon",
      "Spicy Notes",
      "Rose",
      "Amber",
      "Leather",
      " Woody Notes",
      "Indian Patchouli",
    ],
    image: "@/src/images/1million.jpg",
    link: "https://www.amazon.co.uk/Paco-Rabanne-Million-Eau-Toilette/dp/B002XQ1X4G/ref=sr_1_1?crid=3R1YICTYRRZOX&keywords=paco+rabanne+one+million&qid=1697566128&sprefix=Paco%2Caps%2C112&sr=8-1",
    occasion: "Night Out",
    season: "spring",
  },
  {
    id: 32,
    name: "Moustache",
    brand: "Rochas",
    perfumer: "Natalie Gracia-Cetto",
    scentProfile: [
      "Pink Pepper",
      "Mandarin Orange",
      "Atlas Cedar",
      "Bulgarian Rose",
      "Benzoin",
      "Vanilla",
      "Patchouli",
    ],
    image: "@/src/images/Rochas.jpg",
    link: "https://www.amazon.co.uk/dp/B07HK4ZNLQ?ref=nb_sb_ss_w_as-reorder-t1_k9_1_6&amp=&crid=2LWDE7ORKY72I&amp=&sprefix=rochas",
    occasion: "Night Out",
    season: "winter",
  },
  {
    id: 33,
    name: "Acqua di Gio Profumo",
    perfumer: "Alberto Morillas",
    brand: "Giorgio Armani",
    scentProfile: [
      "Sea Notes",
      "Bergamot",
      "Rosemary",
      "Sage",
      "Geranium",
      "Incense",
      "Patchouli",
    ],
    season: "summer",
    image: "@/src/images/ADG.jpg",
    link: "https://www.superdrug.com/fragrance/fragrance-for-him/mens-aftershave/giorgio-armani-aqua-di-gio-profumo-edp-refill-75ml/p/819720?msclkid=fde692829ab11b847622f7ac554f353a&utm_source=bing&utm_medium=cpc&utm_campaign=Superdrug-UK-PLA-Combined-All-All-SE-NC-Metoda-GSC-Fragrance&utm_term=4583863989899416&utm_content=Fragrance%20-%20Low%20Converting&gclid=fde692829ab11b847622f7ac554f353a&gclsrc=3p.ds",
  },
  {
    id: 34,
    name: "Green Irish Tweed",
    perfumer: "Olivier Creed & Pierre Bourdon",
    brand: "Creed",
    scentProfile: [
      "Lemon Verbena",
      "Iris",
      "Violet Leaf",
      "Ambergris",
      "Sandalwood",
    ],
    image: "@/src/images/GreenIrishTweed.jpg",
    link: "https://www.johnlewis.com/creed-green-irish-tweed-eau-de-parfum/p3311377?size=50ml&s_ppc=5dx92700074071294720_mixed_fashion_BAU&tmad=c&tmcampid=2&gclid=26bb437619e51afab1002658c9b47be9&gclsrc=3p.ds&msclkid=26bb437619e51afab1002658c9b47be9",
    season: "summer",
  },
  {
    id: 35,
    name: "Ombre Leather",
    perfumer: "Sonia Constant",
    brand: "Tom Ford",
    scentProfile: [
      "Cardamom",
      "Leather",
      "Jasmine Sambac",
      "Amber",
      "Moss",
      "Patchouli",
    ],
    image: "@/src/images/Ombre-Leather.jpg",
    season: "winter",
    link: "https://www.johnlewis.com/tom-ford-ombre-leather-eau-de-parfum/p3745635",
  },
];
export default aftershave;
